import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'data/network/dio_client.dart';
import 'pages/home_page.dart';
import 'services/analytics_service.dart';
import 'services/video_api_service.dart';
import 'services/app_state.dart';
import 'services/react_bridge.dart';
import 'services/toast_service.dart';