// scene.js
const bgStyle = (v, theater) => ({ background: theater ? '#000' : `linear-gradient(180deg,${v.background.top},${v.background.bottom})`, transition: 'background .8s ease' });
const Badge = ({ v }) => html`<span class="rounded-full border border-white/30 bg-white/15 px-2 py-0.5 text-[11px] uppercase tracking-wider">
  <i class=${'fa-solid ' + v.icon + ' mr-1'}></i>${v.type === '2d' ? '2D' : '3D'} scene · ${v.category}</span>`;
const Fact = ({ v }) => html`<p class="mt-3 border-l-4 border-white/60 pl-3 text-sm italic opacity-90">${v.fact}</p>`;
const PercentBar = ({ pct }) => html`<div class="absolute inset-x-1 bottom-1 h-1.5 overflow-hidden rounded bg-white/20"><div class="h-full bg-emerald-400" style=${{ width: pct + '%' }}></div></div>`;

function ModelCanvas({ src, v }) {
  const ref = useRef(), [pct, setPct] = useState(0);
  useEffect(() => { const el = ref.current, f = e => setPct(e.detail.totalProgress * 100);
    el.addEventListener('progress', f); return () => el.removeEventListener('progress', f); }, []);
  return html`<div class="pointer-events-none absolute bottom-2 right-2 h-32 w-32 rounded-lg bg-slate-900/60">
    <model-viewer ref=${ref} src=${src} auto-rotate="" camera-controls="" camera-orbit=${'45deg 65deg ' + Math.round(v.cameraDistance * 11) + '%'} class="h-full w-full"></model-viewer>
    ${pct < 100 && html`<${PercentBar} pct=${pct}/>`}</div>`;
}

function LiveMetrics({ v, api }) {
  const [d, setD] = useState(null);
  useEffect(() => { const load = () => fetch(`${api}/api/videos/${v.id}/live-data`).then(r => r.json()).then(setD).catch(() => {});
    load(); const t = setInterval(load, 30000); return () => clearInterval(t); }, []);
  return html`<div class="mt-3 rounded-lg border border-white/15 bg-black/40 px-3 py-2 text-xs backdrop-blur">
    <div class="font-semibold text-emerald-300"><i class="fa-solid fa-chart-simple mr-1"></i>Live video metrics</div>
    <div class="mt-1 flex gap-4">${d ? html`<span>▶ ${d.plays} plays</span><span>🔖 ${d.bookmarks} bookmarks</span><span>🎙 ${d.sessions} AI sessions</span>` : 'Syncing…'}</div></div>`;
}

function PdfButton({ v, marks }) {
  const make = () => { const doc = new window.jspdf.jsPDF(), L = t => doc.splitTextToSize(t, 170);
    doc.setFontSize(10).text((v.type + ' scene report').toUpperCase(), 20, 20);
    doc.setFontSize(20).text(L(v.title), 20, 32);
    doc.setFontSize(12).text(L('Category: ' + v.category), 20, 50).text(L(v.context), 20, 62).text(L('Insight: ' + v.fact), 20, 90);
    doc.text(L('Bookmarks: ' + (marks.length ? marks.map(fmt).join(', ') : 'none')), 20, 120);
    doc.setFontSize(9).text('Generated by Microservice TV - ' + new Date().getFullYear(), 20, 280);
    doc.save(v.id + '-report.pdf'); emit({ type: 'pdf_export', id: v.id }); };
  return html`<button onClick=${make} class="mt-3 rounded border border-white/30 bg-white/10 px-3 py-1 text-xs hover:bg-white/20"><i class="fa-solid fa-file-pdf mr-1"></i>Export PDF report</button>`;
}
